### ISSUE TITLE
Method for Removing Timekit User

### ISSUE THREAD

**Issue by ErikPeterson** [timekit-io/js-sdk#11]
Erik from Sweden Unlimited here. I'm looking for a way to set up a testing account to use in unit testing our Timekit based scheduling app. In order for this to work, I have to be able to either delete users or delete an app wholesale to clear the users. Since there's no DELETE route for either of those resources, it doesn't seem that there's a clean way to do this at the moment. 

UPDATE

I see that there is now a 'DELETE' route for apps in the SDK. However, when I attempt to use this method to delete a test app, the API responds with a 404 error. Is the delete route for apps not actually implemented?

**Comment by laander** [comment]
Sorry about the late reply here Erik, missed the notification. Please see my direct email. 

There is indeed a `[DELETE] /apps/:slug` endpoint, but it lacked documentation. 
It has now been added: http://developers.timekit.io/v2/docs/appsslug-1

**Comment by unerh** [comment]
Hi,

Just to follow up on this. Will timekit be providing an endpoint to delete individual users at all? Or is there a workaround for this currently? As I cannot reuse the same test email addresses that was used to test on the booking.js website. Seems like those emails/users are now reserved for Booking.js demo app.

Regards,
Hakan

**Comment by mgauthier** [comment]
+1
