### ISSUE TITLE
500 Error on POST /events endpoint

### ISSUE THREAD

**Issue by ErikPeterson** [timekit-io/js-sdk#13]
When attempting to create a new event for a user, I receive a 500 error in response.

Sample request body with UUID obfuscated:

````
{      
        start: 'Wed Nov 11 2015 15:34:45 GMT-0500 (EST)',
        end: 'Wed Nov 11 2015 16:34:45 GMT-0500 (EST)',
        what: 'Appointment with Foo Bar',
        where: 'http://some.url',
        calendar_id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 
}
````

I think perhaps the format of my date time strings is not what the API is expecting, however there isn't any documentation of the correct format for the `start` and `end` properties in the Timekit docs.

**Comment by laander** [comment]
I'm pretty certain that this is due to the timestamp formatting. See here for reference on formatting: http://developers.timekit.io/docs/types--formatting

The default input format is ISO_8601 eg. `2015-05-26T15:39:03+00:00`. 

You can set another input and output format if you prefer, with the following header:
`Timekit-InputTimestampFormat`. If you've already done that, please post that here so I can correlate it with the timestamp you're sending.

**Comment by ErikPeterson** [comment]
Thanks for the help Lasse, I was able to get it going by setting the header with 'U' and generating Unix style timestamps. 

Just wanted to also note that the standard 'toISOString()' method on the Date object in JS returns an ISO 8601 conforming timestamp, but strings in that format are rejected by Timekit when using the default input timestamp format. JS iso timestamps are automatically converted to UTC time, and have milliseconds included, so the lack of a timezone offset or the addition of the milliseconds could be the issue.

**Comment by laander** [comment]
Yeah, you're right ISO 8601 valid timestamps can be either `1994-11-05T08:15:30-05:00` or `1994-11-05T13:15:30Z` (what .toISOString() produces) and we're only supporting the first one per default.

Thanks for the heads up

**Comment by ErikPeterson** [comment]
Hey Lasse, I'm running in to this same issue with no change in my code. Here's the response I'm getting from Timekit, with the identifying information obscured:

```json
{ data: { error: 'Something went wrong! Our fault!' },
  status: 500,
  statusText: 'Internal Server Error',
  headers: 
   { server: 'nginx/1.6.3',
     'content-type': 'application/json',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'cache-control': 'no-cache',
     date: 'Thu, 10 Dec 2015 18:51:10 GMT',
     vary: 'Origin' },
  config: 
   { method: 'post',
     headers: 
      { 'Timekit-App': 'mission360test',
        Authorization: 'Basic xxxxxxxx',
        'Timekit-InputTimestampFormat': 'U',
        'Timekit-Timezone': 'America/New_York',
        'Content-Type': 'application/json;charset=utf-8' },
     transformRequest: [ [Function] ],
     transformResponse: [ [Function] ],
     url: 'https://api.timekit.io/v2/events',
     data: 
      { start: 1449859870,
        end: 1449863470,
        what: 'Mission-360 Appointment with Derp Derpington',
        where: 'http://mission-360.com/appointments/dasfkjsdf4asdlfads',
        calendar_id: 'xxxxxxxxxx' },
     withCredentials: undefined } }
```

I can confirm that the app, calendar, and user in question existed at the time of the request.

**Comment by vistik** [comment]
Hi @ErikPeterson 

We did introduce an error on the `[POST] /events` endpoint, but I have just deployed a fix for that :)

Visti

**Comment by ErikPeterson** [comment]
Great, thanks Visti

**Comment by vistik** [comment]
:+1:
