### ISSUE TITLE
Timekit does not properly format callback urls for google auth

### ISSUE THREAD

**Issue by ErikPeterson** [timekit-io/js-sdk#15]
Steps to reproduce:

1. Obtain oAuth url from TimeKit.accountGoogleSignup(), manually setting the callback URL to include a query parameter. eg: https://app.com/users/1/callback?special_token=xxxxxxx
2. Authenticate with Google using the oAuth sign in flow.
3. Google redirects to Timekit's callback URL for auth
4. Timekit redirects to the callback URL supplied by the original callback, and appends a query string containing the values generated by the auth flow. Instead of parsing the callback URL and adding query parameters, the query string is instead naively tacked on to the end of the URL, resulting in a double query string, eg: https:://app.com/users/1/callback?special_token=xxxxxxx?email=...&token=... etc.

**Comment by vistik** [comment]
Hi Erik

Sorry for the late reply. I will look into this :)

Visti

**Comment by vistik** [comment]
Hi @ErikPeterson 

I have just deployed a fix, could you check now? :)

Visti
