### ISSUE TITLE
GET /events with ISO 8601 format throwing error 422

### ISSUE THREAD

**Issue by hidingmode** [timekit-io/js-sdk#23]
Request:
![image](https://cloud.githubusercontent.com/assets/7817101/21758945/49223462-d67b-11e6-817e-aec724ea9a77.png)

Response:
![image](https://cloud.githubusercontent.com/assets/7817101/21758953/58398202-d67b-11e6-9f8c-0264b42c281c.png)

I checked the date params should be formatted correctly. So what is wrong?

**Comment by vistik** [comment]
Hi @hidingmode 

The problem is that `+` need to url encoded as `%2B`, see an example here:
`/v2/events?start=2017-01-01T00:00:00%2B00:00&end=2018-01-01T00:00:00%2B00:00`

I hope this will solve your problem

Visti
