### ISSUE TITLE
Error on customer confirming tentative group booking

### ISSUE THREAD

**Issue by hidingmode** [timekit-io/js-sdk#24]
So I have a group booking:
![image](https://cloud.githubusercontent.com/assets/7817101/21760924/b0e83c86-d68a-11e6-8ea8-e0f3c2bd22b7.png)

But when I try to post a confirmation:
![image](https://cloud.githubusercontent.com/assets/7817101/21760983/0697a068-d68b-11e6-8b45-b9fd87f1555d.png)

It responded with:
```
{
"error": "Cannot apply action 'confirm' to current state 'initialized'"
}
```

**Comment by vistik** [comment]
hi @hidingmode 

You need to apply the action 'create' to a `group_customer` graph, but I can see our docs is saying 'confirm', could you give `create` a try?

Visti

**Comment by hidingmode** [comment]
Yes, i just found out as well. I was following your documentation which was with 'confirm'.
![image](https://cloud.githubusercontent.com/assets/7817101/21762081/b3a5be10-d691-11e6-81c5-7c301637c5b8.png)
Please correct the documentation. Thanks :)

Also, i suggest putting more images of the graph flow on the documentation as it will better clarify the documentation since there are not just instant and confirm_decline graphs. It was only until i found out i can GET https://api.timekit.io/v2/bookings/graphs/group_customer/diagram to view the graph that i know i should 'create'.
![fc45b9bb-b205-44b2-b6fc-4ce5e20886c7](https://cloud.githubusercontent.com/assets/7817101/21762631/b45c7490-d694-11e6-976c-e1dfdcbd5922.png)
Out of curiosity, why do you need the authorization header for viewing the images?

**Comment by vistik** [comment]
@hidingmode Yeah I have updated the docs :)

I will have a look at adding the images this part of the docs.

Well, there is no really good reason AFAIK - maybe we should change that :)

**Comment by hidingmode** [comment]
The curl command for group_customer_payment flow is also with 'confirm'.

**Comment by vistik** [comment]
@hidingmode where do you see that?

**Comment by hidingmode** [comment]
![image](https://cloud.githubusercontent.com/assets/7817101/21763576/805286f8-d699-11e6-9421-294d7db7624f.png)
