### ISSUE TITLE
Filtering events

### ISSUE THREAD

**Issue by NikolayGalkin** [timekit-io/js-sdk#27]
Hello everyone!

There is a small question. Does API (and SDK) support filtering events by "where" field. For example, I want to find all events for current location ('where' field).

Thanks.

**Comment by laander** [comment]
@NikolayGalkin 

Sorry you haven't gotten a response to your question. We usually only provide support through our Intercom chat on https://admin.timekit.io or via email, so this fell down between the cracks.

If it's still of any relevance to you, the answer to your question is that it's unfortunately not possible to filter on the `where` attribute currently. Please see the list [here](https://developers.timekit.io/reference#bookings-2) (the "Search" info box) for a list of possible searchable attributes.
