### ISSUE TITLE
Resources endpoints?

### ISSUE THREAD

**Issue by dannyfreed** [timekit-io/js-sdk#36]
I'm trying to get resource IDs to include in a `/findtime/team` API call, but I don't see any documentation for how do to that?

Am I missing something?

**Comment by Trolzie** [comment]
Hi @dannyfreed,
apologies for the extremely late response. In case you are still struggling with this, the I need to inform you that our SDK, is in the process of being updated to our latest version of the API. That is the reason we dont have docs on it yet, as we simply arent finished updating the SDK.

We apologize. Let me know if you would like me to ping you when this update has been released.

**Comment by alexanderbh** [comment]
Any update on the new SDK or do we just have to make our own?

**Comment by laander** [comment]
@dannyfreed @alexanderbh 

Support for all the resources endpoints has been released in `v1.14.0`. Please see the README.

The SDK also supports the App key auth approach (as opposed to Resource key), please see [here](https://github.com/timekit-io/js-sdk#app-key) for a more detailed description.
