### ISSUE TITLE
Issue in updating Microsoft Calendar

### ISSUE THREAD

**Issue by DhavalRadhanpara** [timekit-io/js-sdk#46]
I am getting '500 - Internal Server Error' on updating Microsoft Calendar. I updated it with false and it run smooth. But when I try to update it with true there is problem. I have made new account and calendar. We had an old account (we recently changed password of old one and than cleared all permissions); but we got '502 - Bad Gateway'. For google it runs smooth.

**Comment by laander** [comment]
Hi @DhavalRadhanpara , please get in touch using our support chat on timekit.io (or admin.timekit.io) and we'll help you debug 👌
