### ISSUE TITLE
Issue in retrieving availability for Microsoft Calendar

### ISSUE THREAD

**Issue by DhavalRadhanpara** [timekit-io/js-sdk#47]
I have entered an event in Microsoft Calendar. But I am not getting proper time slots. The time slot that is booked on Microsoft Calendar, is shown as available.

**Comment by jariwiklund** [comment]
Hi @DhavalRadhanpara You need to contact yourfriends@timekit.io instead of issuing bug reports here. In any case this issue is on the api and nok the SDK.
