### ISSUE TITLE
Calling updateResource doesn't update resource name

### ISSUE THREAD

**Issue by cdimitroulas** [timekit-io/js-sdk#51]
With a created resource, try the following:
```js
timekit.updateResource({
  id: // resource-id,
  name: 'New name'
})
```

When I do this I am unable to update the `name` field, but I can confirm the update is working correctly as I am able to update the `timezone` field.

**Comment by laander** [comment]
@cdimitroulas The `update` endpoint takes `first_name` and `last_name` parameters, please see https://developers.timekit.io/reference#resources-id 👍

**Comment by cdimitroulas** [comment]
The documentation also says that there is a `name` field in addition to `first_name` and `last_name` though...

**Comment by laander** [comment]
@cdimitroulas Ah, you're right, sorry - that's quite misleading. The `name` field is a computed property, so I'll remove it from the API reference for the update endpoint ✌️
