### ISSUE TITLE
Support for new Availability API endpoints

### ISSUE THREAD

**Issue by tijunoi** [timekit-io/js-sdk#54]
I was trying to check the last activity of this sdk and I see it's using v2 TimeKit API but it doesn't have the new endpoints for Availability nor I see a deprecation notice for the /findTime endpoints.

Is it coming soon?
Thanks.

**Comment by laander** [comment]
@tijunoi The new availability endpoint is called `fetchAvailability` and is the successor to `findTime`. Check out the readme, it's there in the list of endpoint (although quite easy to overlook) :)

**Comment by tijunoi** [comment]
Sorry to have missed it, I really thought I didn’t see it.

**Comment by laander** [comment]
No sweat, as I said, easy to overlook. Especially since it's gotten a new name
